/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import  { useRef, useState }  from "react";
import {   useNavigate } from "react-router-dom";
import { motion } from "framer-motion-3d";
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export    function Building({gesture}) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/holo_solo_anime.glb')
  
  
  const { actions, names } = useAnimations(animations, group);


  const navigate = useNavigate();
  const [isClicked, setIsClicked] = useState(true);



  const handleCalloutClick = () => {
    console.log(isClicked);
    setIsClicked(!isClicked);
    names.forEach((name) => {
      const action = actions[name];

      if (!isClicked) {
        action.timeScale = -2;
        action.paused = false;
        action.repetitions = 1;
        action.reset().play().clampWhenFinished = true;
      } else {
        action.timeScale = 2;
        // action.paused = false;
        action.repetitions = 1;
        action.reset().play().clampWhenFinished = true;
      }
    });

     navigate('/building' )

  };


  const [victoryHandled, setVictoryHandled] = useState(false);

  useFrame(( ) => {
    // console.log(noHand);

    if (gesture === "Pointing_Up" && !victoryHandled) {
      setVictoryHandled(true);
      setIsClicked(!isClicked);

      names.forEach((name) => {
        const action = actions[name];
        action.timeScale = -2;
        action.paused = false;
        action.repetitions = 1;
        action.reset().play().clampWhenFinished = true;
      });
    }
    if (gesture === "Closed_Fist" && victoryHandled) {
      setVictoryHandled(false);
      setIsClicked(false);

      names.forEach((name) => {
        const action = actions[name];
        action.timeScale = 2;
        action.repetitions = 1;
        action.reset().play().clampWhenFinished = true;
      });
    }
  }, []);


  return (
    <motion.group 
    ref={group}   
    dispose={null} 
    onClick={handleCalloutClick}
    whileHover={{scale:0.85 , originX:0.5}}
    position={[20,12,-191]}
    scale={0.8}
    >
      <group name="Scene">

        <group
          name="building01"
          position={[-72.37, 50.191, 116.791]}
          rotation={[0, -1.571, 0]}
          scale={35.081}
          
  
          >
          <mesh
            name="Plane020"
            castShadow
            receiveShadow
            geometry={nodes.Plane020.geometry}
            material={materials['1.005']}
          />
          <mesh
            name="Plane020_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_1.geometry}
            material={materials['1.001']}
          />
          <mesh
            name="Plane020_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_2.geometry}
            material={materials['1.004']}
          />
          <mesh
            name="Plane020_3"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_3.geometry}
            material={materials['1.002']}
          />
          <mesh
            name="Plane020_4"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_4.geometry}
            material={materials.seam4}
          />
          <mesh
            name="Plane020_5"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_5.geometry}
            material={materials['1 seam']}
          />
          <mesh
            name="Plane020_6"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_6.geometry}
            material={materials['1 kaki']}
          />
          <mesh
            name="Plane020_7"
            castShadow
            receiveShadow
            geometry={nodes.Plane020_7.geometry}
            material={materials.rood_sol}
          />
        </ group>
        <group
          name="building01-glass"
          position={[-61.552, 46.649, 117.011]}
          rotation={[0, -1.571, 0]}
          scale={35.081}>
          <mesh
            name="Plane001"
            castShadow
            receiveShadow
            geometry={nodes.Plane001.geometry}
            material={materials['2 glass']}
          />
          <mesh
            name="Plane001_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_1.geometry}
            material={materials['1 glass frame']}
          />
          <mesh
            name="Plane001_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane001_2.geometry}
            material={materials['glass.010']}
          />
        </group>
        <group
          name="building01-header"
          position={[0.438, 110.22, 116.892]}
          rotation={[0, -1.571, 0]}
          scale={35.081}>
          <mesh
            name="Plane002"
            castShadow
            receiveShadow
            geometry={nodes.Plane002.geometry}
            material={materials['Material.022']}
          />
          <mesh
            name="Plane002_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane002_1.geometry}
            material={materials['1']}
          />
        </group>
        <group
          name="building01-pole"
          position={[0.396, 66.629, 116.963]}
          rotation={[0, -1.571, 0]}
          scale={35.081}>
          <mesh
            name="Plane003"
            castShadow
            receiveShadow
            geometry={nodes.Plane003.geometry}
            material={materials.silver}
          />
          <mesh
            name="Plane003_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane003_1.geometry}
            material={materials['seam.001']}
          />
          <mesh
            name="Plane003_2"
            castShadow
            receiveShadow
            geometry={nodes.Plane003_2.geometry}
            material={materials['Material.133']}
          />
        </group>
        <group
          name="floor_7"
          position={[-72.67, -77.025, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={32.352}>
          <mesh
            name="Plane036"
            castShadow
            receiveShadow
            geometry={nodes.Plane036.geometry}>
              <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
            </mesh>
           
          <mesh
            name="Plane036_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane036_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>
        <group
          name="floor_6"
          position={[-72.67, -61.865, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={32.352}>
          <mesh
            name="Plane037"
            castShadow
            receiveShadow
            geometry={nodes.Plane037.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
          <mesh
            name="Plane037_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane037_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>
        <group
          name="floor_5"
          position={[-72.67, -46.786, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={32.352}>
          <mesh
            name="Plane038"
            castShadow
            receiveShadow
            geometry={nodes.Plane038.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
          <mesh
            name="Plane038_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane038_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>
        <group
          name="floor_4"
          position={[-72.67, -31.881, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={32.352}>
          <mesh
            name="Plane039"
            castShadow
            receiveShadow
            geometry={nodes.Plane039.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
          <mesh
            name="Plane039_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane039_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>
        <group
          name="floor_3"
          position={[-72.67, -16.802, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={32.352}>
          <mesh
            name="Plane041"
            castShadow
            receiveShadow
            geometry={nodes.Plane041.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
          <mesh
            name="Plane041_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane041_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>
        <group
          name="floor_2"
          position={[-72.67, -1.897, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={32.352}>
          <mesh
            name="Plane042"
            castShadow
            receiveShadow
            geometry={nodes.Plane042.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
          <mesh
            name="Plane042_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane042_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>
        <group
          name="floor_1"
          position={[-72.67, 13.182, 117.367]}
          rotation={[0, -1.571, 0]}
          scale={2.696}>
          <mesh
            name="Plane035"
            castShadow
            receiveShadow
            geometry={nodes.Plane035.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
          <mesh
            name="Plane035_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane035_1.geometry}>
            <meshPhongMaterial transparent opacity={0.4} color={"#09DBF7"} />
          </mesh>
        </group>

        <mesh
          name="red-area"
          castShadow
          receiveShadow
          geometry={nodes['red-area'].geometry}
          material={materials['Material.008']}
          position={[-77.093, 16.167, 104.673]}
          scale={[8.664, 5.103, 10.046]}
        />
      </group>
    </motion.group>
  )
}

useGLTF.preload('/holo_solo_anime.glb')
