/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion-3d";
import { AlertOutlined } from "@ant-design/icons";

export function Building(props) {
  const { nodes, materials } = useGLTF('/2503demo-building-solo-.glb')

  const navigate = useNavigate();

  const handleCalloutClick = () => {
    // Navigate to the desired route
     navigate('/building' )
  };
  return (
    <group {...props} dispose={null}>
      <motion.group
        name="building01"
        position={[-70.94, 1.414, 116.986]}
        rotation={[0, -1.571, 0]}
        scale={35.081}
        onClick={handleCalloutClick}
        whileHover={{scale:39 }}
      >
        <mesh
          name="Plane020"
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials['1.005']}
        />
        <mesh
          name="Plane020_1"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_1.geometry}
          material={materials['1.001']}
        />
        <mesh
          name="Plane020_2"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_2.geometry}
          material={materials['1.004']}
        />
        <mesh
          name="Plane020_3"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_3.geometry}
          material={materials['1.002']}
        />
        <mesh
          name="Plane020_4"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_4.geometry}
          material={materials.seam4}
        />
        <mesh
          name="Plane020_5"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_5.geometry}
          material={materials['2 glass']}
        />
        <mesh
          name="Plane020_6"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_6.geometry}
          material={materials['1 glass frame']}
        />
        <mesh
          name="Plane020_7"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_7.geometry}
          material={materials['glass.010']}
        />
        <mesh
          name="Plane020_8"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_8.geometry}
          material={materials['1 seam']}
        />
        <mesh
          name="Plane020_9"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_9.geometry}
          material={materials['1 kaki']}
        />
        <mesh
          name="Plane020_10"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_10.geometry}
          material={materials['Material.022']}
        />
        <mesh
          name="Plane020_11"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_11.geometry}
          material={materials['1']}
        />
        <mesh
          name="Plane020_12"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_12.geometry}
          material={materials.silver}
        />
        <mesh
          name="Plane020_13"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_13.geometry}
          material={materials['seam.001']}
        />
        <mesh
          name="Plane020_14"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_14.geometry}
          material={materials['Material.133']}
        />
        <mesh
          name="Plane020_15"
          castShadow
          receiveShadow
          geometry={nodes.Plane020_15.geometry}
          material={materials.rood_sol}
        />
      </motion.group>
    </group>
  )
}

useGLTF.preload('/2503demo-building-solo-.glb')
