/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 omantel-building.glb 
*/
import  { useRef, useState }  from "react";
import {   useNavigate } from "react-router-dom";
import { motion } from "framer-motion-3d";
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";


export   function Building2() {
  const { nodes, materials } = useGLTF('/omantel-building.glb')
  const stripe = useRef()
  const light = useRef()



  useFrame((state, delta) => {
    const t = (0.5 + Math.sin(state.clock.elapsedTime * 5)) / 22
    stripe.current.color.setRGB(32, 11 + t * 22   , 2 + t * 61)
     light.current.intensity = 0.1 + t * 22
  })


  const navigate = useNavigate();
  const [isClicked, setIsClicked] = useState(true);



  const handleCalloutClick = () => {
    console.log(isClicked);
    setIsClicked(!isClicked);
 
     navigate('/building' )

  };



  return (
    <motion.group       
    onClick={handleCalloutClick}
    whileHover={{scale:1.1 , originX:0.5}}

    >
      <group position={[-54.503, 47.812, -17.067]} rotation={[-Math.PI, 0, -Math.PI]} scale={[79.145, 39.515, 106.143]}>
        <mesh geometry={nodes.Cylinder019.geometry} material={materials['stripe.002']} />
        <mesh geometry={nodes.Cylinder019_1.geometry} material={materials['gray.003']} />
        <mesh geometry={nodes.Cylinder019_2.geometry} material={materials['dgray.002']} />
        <mesh geometry={nodes.Cylinder019_3.geometry} material={materials['concrt.002']} />
        <mesh geometry={nodes.Cylinder019_4.geometry} material={materials['glass.004']} />
        <mesh geometry={nodes.Cylinder019_5.geometry} material={materials['window_text.002']} />
        <mesh geometry={nodes.Cylinder019_6.geometry} material={materials['Material.018']} />
        <mesh geometry={nodes.Cylinder019_7.geometry} material={materials['green.002']} />
        <mesh geometry={nodes.Cylinder019_8.geometry} material={materials['roof.002']} />
      </group>

      <mesh 
      geometry={nodes.building_omantel_tube.geometry} 
      // material={materials['neon.002']} 
      position={[-54.503, 47.812, -17.067]} 
      rotation={[-Math.PI, 0, -Math.PI]} 
      scale={[79.145, 39.515, 106.143]} >


                  <meshBasicMaterial ref={stripe} toneMapped={false} />
                  <pointLight ref={light} intensity={0.1} color={[10, 2, 5]} distance={2.5} />

      </mesh>
       


    </motion.group>
  )
}

useGLTF.preload('/omantel-building.glb')
