/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 demo-diorama2.glb -T 
Files: demo-diorama2.glb [167.26MB] > demo-diorama2-transformed.glb [12.63MB] (92%)
*/

 import { useGLTF } from '@react-three/drei'
 import { motion } from "framer-motion-3d";
import { Building3 } from './Building3';

export default function ModelOmantel4({ landx, landz, gesture, noHand }) {
  const { nodes, materials } = useGLTF('/demo-diorama2-transformed.glb')


  return (

    <motion.group
      dispose={null}
      // scale={12}
      position={[0,-70,10]}
      initial={{ rotateX: 0, scale: 0 }}
      animate={{
        scale: Math.max(0.8, noHand ? 0.8 : -landz /7  ),
        rotateY: -landx }}
      transition={{ duration: 1, ease: "easeOut" }}
      exit= {{ scale:0, transition:{duration: 0.5, ease:"easeInOut", delay:0.3} }}
    >
     <Building3 gesture={gesture}/>

    <group dispose={null}>
      <group position={[-23.652, 3.744, 179.988]} rotation={[0, -1.571, 0]} scale={22.084}>
        <mesh geometry={nodes.Plane020.geometry} material={materials.PaletteMaterial003} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials.PaletteMaterial001} />
        <mesh geometry={nodes.Plane020_3.geometry} material={materials.PaletteMaterial002} />
      </group>
      <mesh geometry={nodes.building03.geometry} material={materials.PaletteMaterial005} position={[-743.026, 7.742, 86.294]} rotation={[0, -1.571, 0]} scale={14.834} />
      <group position={[-458.427, 9.801, 315.208]} rotation={[0, 1.571, 0]} scale={[2.95, 3.093, 3.093]}>
        <mesh geometry={nodes.Mesh044.geometry} material={materials.StoneTile} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={materials.PaletteMaterial007} />
        <mesh geometry={nodes.Mesh044_2.geometry} material={materials.PaletteMaterial006} />
      </group>
      <mesh geometry={nodes.Plane131.geometry} material={nodes.Plane131.material} position={[99.787, 11.967, -185.323]} />
      <group position={[-508.649, 1.316, -406.012]} rotation={[-Math.PI, 1.514, -Math.PI]} scale={34.647}>
        <mesh geometry={nodes.Mesh034.geometry} material={materials.PaletteMaterial008} />
        <mesh geometry={nodes.Mesh034_1.geometry} material={materials.PaletteMaterial010} />
        <mesh geometry={nodes.Mesh034_2.geometry} material={materials['wall.002']} />
        <mesh geometry={nodes.Mesh034_3.geometry} material={materials.PaletteMaterial009} />
        <mesh geometry={nodes.Mesh034_4.geometry} material={materials['ppl-texture']} />
      </group>
      <instancedMesh args={[nodes.Plane089.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Plane089.instanceMatrix} />
      <instancedMesh args={[nodes.Plane089_1.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Plane089_1.instanceMatrix} />
      <instancedMesh args={[nodes.Plane163.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Plane163.instanceMatrix} />
      <instancedMesh args={[nodes.Plane163_1.geometry, materials.PaletteMaterial001, 5]} instanceMatrix={nodes.Plane163_1.instanceMatrix} />
    </group>


</motion.group>

  )
}

useGLTF.preload('/demo-diorama2-transformed.glb')
