/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 diorama-omantelhq-v2024-v08-4.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function ModelOmantel2(props) {

  const { nodes, materials } = useGLTF('/diorama-omantelhq-v2024-v08-4.glb')
  // const matRef = useRef();
  // useFrame(({ clock }) => {
  //    matRef.current.emissiveIntensity = Math.abs(
  //     Math.sin(clock.elapsedTime * 0.5)
  //   );
  // });
  const stripe = useRef()
  const light = useRef()
  // useFrame((state, delta) => {
  //   const t = (1 + Math.sin(state.clock.elapsedTime * 2)) / 2
  //   stripe.current.color.setRGB(2 + t * 20, 2, 20 + t * 50)
  //    light.current.intensity = 0.3 + t * 4
  // })



  return (
    <group {...props} dispose={null}>
      <group position={[119.729, 1.414, -292.892]} rotation={[0, -1.571, 0]} scale={22.197}>
        <mesh geometry={nodes.Plane020.geometry} material={materials['1.005']} />
        <mesh geometry={nodes.Plane020_1.geometry} material={materials['1.001']} />
        <mesh geometry={nodes.Plane020_2.geometry} material={materials['1.004']} />
        <mesh geometry={nodes.Plane020_3.geometry} material={materials['1.002']} />
        <mesh geometry={nodes.Plane020_4.geometry} material={materials.seam4} />
        <mesh geometry={nodes.Plane020_5.geometry} material={materials['2 glass']} />
        <mesh geometry={nodes.Plane020_6.geometry} material={materials['1 glass frame']} />
        <mesh geometry={nodes.Plane020_7.geometry} material={materials['glass.010']} />
        <mesh geometry={nodes.Plane020_8.geometry} material={materials['1 seam']} />
        <mesh geometry={nodes.Plane020_9.geometry} material={materials['1 kaki']} />
        <mesh geometry={nodes.Plane020_10.geometry} material={materials['Material.022']} />
        <mesh geometry={nodes.Plane020_11.geometry} material={materials['1']} />
        <mesh geometry={nodes.Plane020_12.geometry} material={materials.silver} />
        <mesh geometry={nodes.Plane020_13.geometry} material={materials['seam.001']} />
        <mesh geometry={nodes.Plane020_14.geometry} material={materials['Material.133']} />
        <mesh geometry={nodes.Plane020_15.geometry} material={materials.rood_sol} />
      </group>
      <group position={[52.306, 3.307, 79.303]} rotation={[-Math.PI, 0, -Math.PI]} scale={[15.987, 15.987, 17.239]}>
        <mesh geometry={nodes.Cube032.geometry} material={materials['Material.134']} />
        <mesh geometry={nodes.Cube032_1.geometry} material={materials['Material.148']} />
        <mesh geometry={nodes.Cube032_2.geometry} material={materials['Material.149']} />
        <mesh geometry={nodes.Cube032_3.geometry} material={materials['Material.150']} />
        <mesh geometry={nodes.Cube032_4.geometry} material={materials['Material.151']} />
        <mesh geometry={nodes.Cube032_5.geometry} material={materials.kaki} />
        <mesh geometry={nodes.Cube032_6.geometry} material={materials['frame.006']} />
        <mesh geometry={nodes.Cube032_7.geometry} material={materials['2 glass']} />
        <mesh geometry={nodes.Cube032_8.geometry} material={materials['Material.152']} />
        <mesh geometry={nodes.Cube032_9.geometry} material={materials['lite-gray']} />
        <mesh geometry={nodes.Cube032_10.geometry} material={materials['dk-gray']} />
        <mesh geometry={nodes.Cube032_11.geometry} material={materials['Material.153']} />
        <mesh geometry={nodes.Cube032_12.geometry} material={materials['Material.154']} />
        <mesh geometry={nodes.Cube032_13.geometry} material={materials['Material.155']} />
        <mesh geometry={nodes.Cube032_14.geometry} material={materials['Material.156']} />
      </group>
      <group position={[-13.797, 7.742, -251.054]} rotation={[0, -1.571, 0]} scale={14.834}>
        <mesh geometry={nodes.Cube033.geometry} material={materials['1.003']} />
        <mesh geometry={nodes.Cube033_1.geometry} material={materials['2 glass']} />
        <mesh geometry={nodes.Cube033_2.geometry} material={materials['3']} />
        <mesh geometry={nodes.Cube033_3.geometry} material={materials['Material.157']} />
      </group>
      <group position={[-141.343, 9.801, -181.863]} rotation={[0, 1.571, 0]} scale={[2.95, 3.093, 3.093]}>
        <mesh geometry={nodes.Mesh044.geometry} material={materials['CRN.Material #168']} />
        <mesh geometry={nodes.Mesh044_1.geometry} material={materials.aluminum2} />
        <mesh geometry={nodes.Mesh044_2.geometry} material={materials['CRN.Material #166']} />
        <mesh geometry={nodes.Mesh044_3.geometry} material={materials['CRN.rMat016']} />
        <mesh geometry={nodes.Mesh044_4.geometry} material={materials.StoneTile} />
        <mesh geometry={nodes.Mesh044_5.geometry} material={materials['CRN.Material #167']} />
        <mesh geometry={nodes.Mesh044_6.geometry} material={materials['CRN.Material #165']} />
        <mesh geometry={nodes.Mesh044_7.geometry} material={materials['glass.011']} />
        <mesh geometry={nodes.Mesh044_8.geometry} material={materials['Material.162']} />
        <mesh geometry={nodes.Mesh044_9.geometry} material={materials['Material.163']} />
      </group>
      <mesh geometry={nodes.Plane130.geometry} material={materials.GRAY2} position={[98.764, 11.004, -184.553]} />
      <mesh geometry={nodes.Plane131.geometry} material={nodes.Plane131.material} position={[99.787, 11.967, -185.323]} />
      <group position={[93.18, 11.807, -183.43]}>
        <mesh geometry={nodes.Plane135_1.geometry} material={materials['Material.126']} />
        <mesh geometry={nodes.Plane135_2.geometry} material={materials['Material.127']} />
      </group>
      <mesh geometry={nodes.Plane133.geometry} material={materials['Material.006']} position={[54.809, 10.085, -186.825]} scale={10.972} />
      <mesh geometry={nodes.Plane134.geometry} material={materials['Material.006']} position={[54.809, 10.085, -186.825]} scale={10.972} />
      <group position={[-82.207, 18.253, -300.726]}>
        <mesh geometry={nodes.Plane134_1.geometry} material={materials['Material.126']} />
        <mesh geometry={nodes.Plane134_2.geometry} material={materials['Material.127']} />
      </group>
      <mesh geometry={nodes.Plane143.geometry} material={materials['Material.129']} position={[244.339, 4.857, 447.661]} scale={56.051} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.GRAY2} position={[278.335, 5.01, 398.114]} scale={[5.629, 2.888, 5.629]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.GRAY2} position={[273.119, 7.94, 451.539]} scale={[5.629, 2.888, 5.629]} />
      <group position={[464.813, 4.589, -21.534]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.849, 0.849, 1.213]}>
        <mesh geometry={nodes.Plane146.geometry} material={materials['Material.126']} />
        <mesh geometry={nodes.Plane146_1.geometry} material={materials['Material.127']} />
      </group>
      <mesh geometry={nodes.Plane145.geometry} material={materials['Material.119']} position={[464.813, 4.501, -21.534]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.849, 0.849, 1.213]} />
      <mesh geometry={nodes.Plane147.geometry} material={materials['Material.121']} position={[457.154, 5.306, -19.52]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.849, 0.849, 1.213]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.130']} position={[226.802, 5.052, 418.884]} scale={[57.609, 2.118, 15.222]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials['Material.135']} position={[-258.491, 11.476, -305.336]} scale={10.445} />
      <mesh geometry={nodes.Cube014.geometry} material={materials['Material.135']} position={[228.627, 5.557, -294.597]} scale={11.001} />
      <mesh geometry={nodes.Plane082.geometry} material={materials['Material.055']} position={[-817.344, 4.074, 491.81]} rotation={[0, -1.571, 0]} scale={62.566} />
      <group position={[552.27, 4.289, 406.037]} rotation={[0, -1.223, 0]} scale={0.471}>
        <mesh geometry={nodes.Plane070_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane070_2.geometry} material={materials['Material.013']} />
      </group>
      <mesh geometry={nodes.Plane021.geometry} material={materials['Material.004']} position={[407.271, 4.014, 512.699]} rotation={[0, -1.209, 0]} scale={0.471} />
      <group position={[552.27, 4.289, 199.481]} rotation={[0, -1.223, 0]} scale={0.471}>
        <mesh geometry={nodes.Plane071.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane071_1.geometry} material={materials['Material.013']} />
      </group>
      <group position={[552.27, 4.289, -6.486]} rotation={[0, -1.223, 0]} scale={0.471}>
        <mesh geometry={nodes.Plane072_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane072_2.geometry} material={materials['Material.013']} />
      </group>
      <group position={[552.27, 4.289, 612.821]} rotation={[0, -1.223, 0]} scale={0.471}>
        <mesh geometry={nodes.Plane026.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane026_1.geometry} material={materials['Material.013']} />
      </group>
      <mesh geometry={nodes.base.geometry} material={materials['gray-blue']} position={[406.361, 4.014, 512.699]} scale={90.453} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.114']} position={[90.098, 6.69, -49.618]} scale={90.453} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.114']} position={[159.307, 10.024, -102.993]} scale={90.453} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['gray-blue']} position={[-451.15, 2.053, -582.427]} scale={90.453} />
      <mesh geometry={nodes.Cube006.geometry} material={materials.GRAY2} position={[406.361, 4.014, 512.699]} scale={90.453} />
      <mesh geometry={nodes.Cube007.geometry} material={materials['Material.114']} position={[119.472, 9.558, -165.297]} scale={90.453} />
      <mesh geometry={nodes.Cube008.geometry} material={materials['Material.114']} position={[59.559, 9.558, -165.297]} scale={90.453} />
      <mesh geometry={nodes.Cube015.geometry} material={materials['Material.114']} position={[406.361, 4.014, 512.699]} scale={90.453} />
      <mesh geometry={nodes.Cube016.geometry} material={materials['Material.114']} position={[406.361, 4.014, 512.699]} scale={90.453} />
      <mesh geometry={nodes.Plane005.geometry} material={materials['road-01']} position={[407.271, 4.014, 512.699]} rotation={[0, -0.032, 0]} scale={3.504} />
      <mesh geometry={nodes.Circle.geometry} material={materials.stone} position={[407.271, 4.014, 512.699]} rotation={[0, -0.582, 0]} scale={[6.139, 6.139, 4.704]} />
      <mesh geometry={nodes.Plane008.geometry} material={materials['Material.011']} position={[407.271, 4.014, 512.699]} rotation={[0, -0.582, 0]} scale={3.984} />
      <mesh geometry={nodes.Plane009.geometry} material={materials.stone} position={[407.271, 4.014, 512.699]} rotation={[0, -0.582, 0]} scale={3.984} />
      <mesh geometry={nodes.Plane012.geometry} material={materials['Material.013']} position={[406.448, 4.014, 514.51]} rotation={[0, -0.676, 0]} scale={6.023} />
      <mesh geometry={nodes.Plane015.geometry} material={materials['Material.004']} position={[407.271, 4.014, 512.699]} rotation={[0, 0.02, 0]} scale={2.425} />
      <mesh geometry={nodes.Plane016.geometry} material={materials['Material.003']} position={[407.271, 4.014, 512.699]} rotation={[0, 0.02, 0]} scale={2.425} />
      <mesh geometry={nodes.rim.geometry} material={materials['Material.001']} position={[407.271, 4.014, 512.699]} rotation={[0, -0.582, 0]} scale={3.984} />
      <mesh geometry={nodes.Circle003.geometry} material={materials['Material.001']} position={[407.271, 4.014, 512.699]} rotation={[0, -0.582, 0]} scale={[6.265, 6.265, 4.8]} />
      <mesh geometry={nodes.Plane006.geometry} material={materials['Material.001']} position={[407.271, 4.014, 512.699]} rotation={[0, 0.093, 0]} scale={2.425} />
      <mesh geometry={nodes.Plane010.geometry} material={materials.stone} position={[493.849, 3.924, 599.823]} rotation={[0, 0.093, 0]} scale={2.425} />
      <mesh geometry={nodes.Plane018.geometry} material={materials['Material.009']} position={[407.271, 4.014, 512.699]} rotation={[0, 0.093, 0]} scale={2.425} />
      <mesh geometry={nodes.Circle002.geometry} material={materials['Material.001']} position={[407.271, 4.014, 512.699]} rotation={[0, 1.237, 0]} scale={[6.139, 6.139, 4.704]} />
      <mesh geometry={nodes.Circle001.geometry} material={materials.stone} position={[407.271, 4.014, 512.699]} rotation={[0, 1.24, 0]} scale={[6.139, 6.139, 4.704]} />
      <mesh geometry={nodes.Plane017.geometry} material={materials['Material.001']} position={[407.271, 4.014, 512.699]} rotation={[0, -1.555, 0]} scale={15.798} />
      <mesh geometry={nodes.Plane019.geometry} material={materials['Material.007']} position={[407.271, 4.014, 512.699]} rotation={[0, -0.655, 0]} scale={0.683} />
      <mesh geometry={nodes.Plane.geometry} material={materials['Material.002']} position={[407.271, 4.014, 512.699]} rotation={[0, 0.083, 0]} scale={2.398} />
      <group position={[534.397, 7.685, 286.921]} rotation={[-Math.PI, 0, 0]} scale={-14.836}>
        <mesh geometry={nodes.Plane040_1.geometry} material={materials['Material.003']} />
        <mesh geometry={nodes.Plane040_2.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane040_3.geometry} material={materials.Trunk} />
      </group>
      <group position={[535.07, 4.531, 329.252]} rotation={[0, 0.02, 0]} scale={2.425}>
        <mesh geometry={nodes.Plane045_1.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Plane045_2.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Plane062.geometry} material={materials['Material.004']} position={[536.238, 4.283, 233.137]} rotation={[0, 0.02, 0]} scale={2.425} />
      <mesh geometry={nodes.Plane063.geometry} material={materials['Material.007']} position={[536.215, 4.318, 233.094]} rotation={[0, -0.655, 0]} scale={0.683} />
      <group position={[535.361, 7.306, 194.857]} rotation={[0, -0.016, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane066.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane066_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[535.361, 7.306, 85.061]} rotation={[0, -0.016, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane067.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane067_1.geometry} material={materials.Trunk} />
      </group>
      <mesh geometry={nodes.Plane025.geometry} material={materials['Material.116']} position={[250.392, 4.067, 300.179]} scale={[37.571, 2.685, 2.685]} />
      <mesh geometry={nodes.Plane029.geometry} material={materials['Material.116']} position={[167.163, 4.067, 300.179]} scale={[37.571, 2.685, 2.685]} />
      <mesh geometry={nodes.Cylinder055.geometry} material={materials['Material.115']} position={[500.765, 7.438, 605.799]} rotation={[0, -0.427, 0]} scale={[0.074, 0.08, 0.066]} />
      <mesh geometry={nodes.Cylinder056.geometry} material={materials['Material.115']} position={[494.129, 7.438, 602.02]} rotation={[-Math.PI, 0.432, -Math.PI]} scale={[0.074, 0.08, 0.066]} />
      <group position={[113.87, 4.633, -126.275]}>
        <mesh geometry={nodes.Mesh.geometry} material={materials['Material.120']} />
        <mesh geometry={nodes.Mesh_1.geometry} material={materials['grass.001']} />
        <mesh geometry={nodes.Mesh_2.geometry} material={materials['Material.118']} />
        <mesh geometry={nodes.Mesh_3.geometry} material={materials['SVGMat.007']} />
      </group>
      <group position={[217.665, 7.809, -6.428]} rotation={[0, 1.319, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane082_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane082_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[212.927, 7.809, 0.083]} rotation={[0, 0.479, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane084.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane084_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[209.655, 7.809, 5.321]} rotation={[0, -0.794, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane085.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane085_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[213.259, 7.809, -9.498]} rotation={[0, 0.132, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane086.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane086_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[208.666, 7.809, -3.823]} rotation={[0, 0.819, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane087.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane087_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[205.249, 7.809, 2.25]} rotation={[0, 1.133, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane089.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane089_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.304, 7.809, -18.71]} rotation={[0, 1.133, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane090.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane090_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.438, 7.809, 26.006]} rotation={[-Math.PI, 0.553, -Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane091.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane091_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.438, 7.809, 52.616]} rotation={[0, -0.763, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane092.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane092_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.438, 7.809, 37.298]} rotation={[0, 1.133, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane095.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane095_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.171, 7.809, 12.694]} rotation={[0, 0.175, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane096.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane096_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.571, 7.809, 78.957]} rotation={[-Math.PI, 0.553, -Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane098.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane098_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[196.304, 7.809, -33.529]} rotation={[0, 0.175, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane103.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane103_1.geometry} material={materials.Trunk} />
      </group>
      <mesh geometry={nodes.Plane069.geometry} material={materials['Material.118']} position={[221.605, 4.16, -185.22]} scale={15.202} />
      <group position={[268.834, 4.159, -99.396]} scale={18.697}>
        <mesh geometry={nodes.Plane107.geometry} material={materials.grass} />
        <mesh geometry={nodes.Plane107_1.geometry} material={materials.gray} />
      </group>
      <group position={[211.629, 7.809, 42.844]} rotation={[-Math.PI, 0.553, -Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane008_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane008_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[53.066, 8.049, 152.145]} rotation={[0, -1.16, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane126_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane126_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[73.217, 8.049, 152.362]} rotation={[0, -0.366, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane127_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane127_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[92.716, 8.049, 152.354]} rotation={[Math.PI, -1.001, Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane128_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane128_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[135.4, 8.049, 152.145]} rotation={[0, -1.16, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane129_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane129_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[155.592, 8.049, 152.255]} rotation={[0, 0.331, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane130_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane130_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[175.194, 8.049, 152.42]} rotation={[0, -1.16, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane131_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane131_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[36.916, 12.946, -189.243]} rotation={[0, 1.133, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane140_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane140_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[37.05, 12.946, -176.464]} rotation={[0, -0.763, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane142.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane142_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[71.451, 12.946, -189.243]} rotation={[0, 1.133, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane143_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane143_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[71.585, 12.946, -176.464]} rotation={[0, -0.763, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane145_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane145_2.geometry} material={materials.Trunk} />
      </group>
      <mesh geometry={nodes.Cylinder023.geometry} material={materials['Material.115']} position={[225.265, 8.744, 421.709]} rotation={[0, 1.571, 0]} scale={[0.154, 0.169, 0.254]} />
      <mesh geometry={nodes.Cylinder024.geometry} material={materials['Material.115']} position={[225.265, 8.744, 416.392]} rotation={[Math.PI, -1.571, 0]} scale={[-0.154, -0.169, -0.254]} />
      <mesh geometry={nodes.sand.geometry} material={materials['gray-blue']} position={[85.583, 3.994, 544.593]} scale={3342.734} />
      <mesh geometry={nodes.road.geometry} material={materials['SVGMat.007']} position={[-1387.158, 4.674, 1337.534]} scale={3342.734} />
      <mesh geometry={nodes.Plane048.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <mesh geometry={nodes.Plane049.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <mesh geometry={nodes.Plane052.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <mesh geometry={nodes.Plane054.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <mesh geometry={nodes.Plane055.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <mesh geometry={nodes.Plane056.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <mesh geometry={nodes.Plane057.geometry} material={materials['Material.004']} position={[406.656, 4.014, 514.542]} rotation={[0, -1.149, 0]} scale={0.469} />
      <group position={[406.361, 4.014, 512.699]} rotation={[Math.PI, 0, Math.PI]} scale={0.435}>
        <mesh geometry={nodes.Crown002_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Crown002_2.geometry} material={materials.Trunk} />
      </group>
      <mesh geometry={nodes.Plane151.geometry} material={materials['Material.126']} position={[361.89, 4.876, 146.76]} rotation={[0, 1.571, 0]} scale={[1, 1, 1.593]} />
      <group position={[155.478, 7.306, -234.904]} rotation={[0, 1.571, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane154_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane154_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[121.87, 7.306, -234.904]} rotation={[0, 1.059, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane156_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane156_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[87.724, 7.306, -234.904]} rotation={[0, 1.059, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane158_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane158_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[60.301, 7.306, -237.288]} rotation={[0, 1.059, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane160.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane160_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[71.951, 7.306, -223.208]} rotation={[0, -1.571, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane161_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane161_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[105.559, 7.306, -223.208]} rotation={[Math.PI, -1.059, Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane163_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane163_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[139.704, 7.306, -223.208]} rotation={[Math.PI, -1.059, Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane165_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane165_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[23.064, 7.306, -241.724]} rotation={[0, 1.059, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane167.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane167_1.geometry} material={materials.Trunk} />
      </group>
      <group position={[22.392, 7.306, -218.065]} rotation={[0, -0.622, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane168_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane168_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[171.606, 7.306, -223.208]} rotation={[0, -1.571, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane170_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane170_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[205.214, 7.306, -223.208]} rotation={[Math.PI, -1.059, Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane172_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane172_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[239.36, 7.306, -223.208]} rotation={[Math.PI, -1.059, Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane174_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane174_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[270.255, 7.306, -223.208]} rotation={[Math.PI, -1.059, Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane176_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane176_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[40.929, 4.064, -229.264]} scale={6.339}>
        <mesh geometry={nodes.Circle001_1.geometry} material={materials['Material.136']} />
        <mesh geometry={nodes.Circle001_2.geometry} material={materials['Material.137']} />
      </group>
      <mesh geometry={nodes.Cube018.geometry} material={materials['gray-blue']} position={[-164.057, 3.719, -1.474]} scale={90.453} />
      <mesh geometry={nodes.Cube019.geometry} material={materials['Material.138']} position={[-620.787, 3.99, 13.76]} scale={[13.287, 15.238, 74.147]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials['Material.140']} position={[-655.627, 7.159, -24.132]} scale={[13.287, 15.238, 74.147]} />
      <mesh geometry={nodes.Cylinder026.geometry} material={materials['Material.115']} position={[-639.644, 7.79, 18.209]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.074, 0.08, 0.061]} />
      <mesh geometry={nodes.Cylinder027.geometry} material={materials['Material.115']} position={[-639.644, 7.79, 56.593]} rotation={[Math.PI, -0.017, Math.PI]} scale={[0.074, 0.08, 0.061]} />
      <mesh geometry={nodes.Cube022.geometry} material={materials['Material.141']} position={[-657.78, 4.272, 17.492]} />
      <group position={[250.601, 3.992, 252.593]} scale={35.491}>
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['Material.146']} />
        <mesh geometry={nodes.Cube012_2.geometry} material={materials['Material.147']} />
      </group>
      <mesh geometry={nodes.Plane030.geometry} material={materials['Material.004']} position={[206.527, 4.283, 148.852]} rotation={[0, 0.02, 0]} scale={2.425} />
      <group position={[205.65, 7.306, 110.572]} rotation={[0, -0.016, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane002_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane002_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[178.89, 3.992, 252.293]} scale={35.491}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Material.146']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['Material.147']} />
      </group>
      <mesh geometry={nodes.Plane032.geometry} material={materials['Material.004']} position={[195.9, 4.283, 271.371]} rotation={[0, 0.02, 0]} scale={2.425} />
      <group position={[195.023, 7.306, 233.091]} rotation={[0, -0.016, 0]} scale={14.836}>
        <mesh geometry={nodes.Plane009_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane009_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[162.096, 4.159, 75.288]} scale={13.309}>
        <mesh geometry={nodes.Plane016_1.geometry} material={materials.grass} />
        <mesh geometry={nodes.Plane016_2.geometry} material={materials.gray} />
      </group>
      <mesh geometry={nodes.NurbsCurve001.geometry} material={materials['Material.118']} position={[113.87, 3.948, -126.275]} />
      <group position={[127.268, 13.014, 89.309]} rotation={[-Math.PI, 0.553, -Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane012_1.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane012_2.geometry} material={materials.Trunk} />
      </group>
      <group position={[123.798, 13.014, 113.276]} rotation={[-Math.PI, 0.555, -Math.PI]} scale={14.836}>
        <mesh geometry={nodes.Plane014.geometry} material={materials.Crown} />
        <mesh geometry={nodes.Plane014_1.geometry} material={materials.Trunk} />
      </group>

      {/* <mesh geometry={nodes.shroud_tube.geometry} material={materials['neon.001']} position={[-39.383, 40.412, -70.722]} rotation={[Math.PI, 0, Math.PI]} scale={[63.422, 31.665, 85.057]} /> */}
      
      <mesh 
      geometry={nodes.shroud_tube.geometry} 
      // material={materials['neon.001']} 
      position={[-39.383, 40.412, -70.722]} 
      rotation={[Math.PI, 0, Math.PI]} 
      scale={[63.422, 31.665, 85.057]} >
        {/* <meshStandardMaterial
        // ref={matRef}
         color={"gold"}
        roughness={0.1}
        metalness={0.5}
         emissive={"gold"}
        emissiveIntensity={11}
      /> */}

          <meshBasicMaterial ref={stripe} toneMapped={false} />
          <pointLight ref={light} intensity={0.3} color={[10, 2, 5]} distance={2.5} />
      </mesh>

      <group position={[-39.383, 71.406, -60.031]} rotation={[Math.PI, 0, Math.PI]} scale={[60.061, 29.987, 60.061]}>
        <mesh geometry={nodes.Cylinder013.geometry} material={materials['concrt.001']} />
        <mesh geometry={nodes.Cylinder013_1.geometry} material={materials['green.001']} />
        <mesh geometry={nodes.Cylinder013_2.geometry} material={materials['roof.001']} />
        <mesh geometry={nodes.Cylinder013_3.geometry} material={materials['gray.002']} />
        <mesh geometry={nodes.Cylinder013_4.geometry} material={materials['dgray.001']} />
        <mesh geometry={nodes.Cylinder013_5.geometry} material={materials['stripe.001']} />
        <mesh geometry={nodes.Cylinder013_6.geometry} material={materials['glass.001']} />
        <mesh geometry={nodes.Cylinder013_7.geometry} material={materials['window_text.001']} />
        <mesh geometry={nodes.Cylinder013_8.geometry} material={materials['Material.008']} />
      </group>
    </group>
  )
}

useGLTF.preload('/diorama-omantelhq-v2024-v08-4.glb')
