/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";
import { Link, useNavigate } from "react-router-dom";
import { motion } from "framer-motion-3d";
import { AlertOutlined } from "@ant-design/icons";
import { Building } from './Building'

export default function Model({ landx, landz, gestures, noHand }) {
  const { nodes, materials } = useGLTF('/demo-transformed.glb')
  return (
    <motion.group
      dispose={null}
      // scale={12}
      position={[0,-80,40]}
      initial={{ rotateX: 0, scale: 0 }}
      animate={{
        scale: Math.max(0.8, noHand ? 0.8 : -landz /7  ),
        rotateY: -landx,
      }}
      transition={{ duration: 1, ease: "easeOut" }}
      exit= {{ scale:0, transition:{duration: 0.5, ease:"easeInOut", delay:0.3} }}
    >
      <group name="Scene">
        <Building gesture={gesture}/>


        <group
          name="building02"
          position={[52.306, 3.307, 79.303]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[15.987, 15.987, 17.239]}>
          <mesh
            name="Cube032"
            castShadow
            receiveShadow
            geometry={nodes.Cube032.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Cube032_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube032_1.geometry}
            material={materials.PaletteMaterial002}
          />
        </group>
        <mesh
          name="building03"
          castShadow
          receiveShadow
          geometry={nodes.building03.geometry}
          material={materials.PaletteMaterial003}
          position={[-13.797, 7.742, -251.054]}
          rotation={[0, -1.571, 0]}
          scale={14.834}
        />
        <group
          name="building04"
          position={[-141.343, 9.801, -181.863]}
          rotation={[0, 1.571, 0]}
          scale={[2.95, 3.093, 3.093]}>
          <mesh
            name="Mesh044"
            castShadow
            receiveShadow
            geometry={nodes.Mesh044.geometry}
            material={materials.StoneTile}
          />
          <mesh
            name="Mesh044_1"
            castShadow
            receiveShadow
            geometry={nodes.Mesh044_1.geometry}
            material={materials.PaletteMaterial005}
          />
          <mesh
            name="Mesh044_2"
            castShadow
            receiveShadow
            geometry={nodes.Mesh044_2.geometry}
            material={materials.PaletteMaterial004}
          />
        </group>
        <mesh
          name="Plane131"
          castShadow
          receiveShadow
          geometry={nodes.Plane131.geometry}
          material={nodes.Plane131.material}
          position={[99.787, 11.967, -185.323]}
        />
        <mesh
          name="Plane005"
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials['road-01']}
          position={[407.271, 4.014, 512.699]}
          rotation={[0, -0.032, 0]}
          scale={3.504}
        />
        <mesh
          name="Circle"
          castShadow
          receiveShadow
          geometry={nodes.Circle.geometry}
          material={materials.stone}
          position={[407.271, 4.014, 512.699]}
          rotation={[0, -0.582, 0]}
          scale={[6.139, 6.139, 4.704]}
        />
        <mesh
          name="Plane008"
          castShadow
          receiveShadow
          geometry={nodes.Plane008.geometry}
          material={materials['Material.011']}
          position={[407.271, 4.014, 512.699]}
          rotation={[0, -0.582, 0]}
          scale={3.984}
        />
        <group>
          <mesh
            name="Plane089"
            castShadow
            receiveShadow
            geometry={nodes.Plane089.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Plane089_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane089_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
        <group>
          <mesh
            name="Plane163"
            castShadow
            receiveShadow
            geometry={nodes.Plane163.geometry}
            material={materials.PaletteMaterial001}
          />
          <mesh
            name="Plane163_1"
            castShadow
            receiveShadow
            geometry={nodes.Plane163_1.geometry}
            material={materials.PaletteMaterial001}
          />
        </group>
      </group>
    </motion.group>
  )
}

useGLTF.preload('/demo-transformed.glb')
