/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, { useRef } from "react";
import { Environment, Html, useGLTF } from "@react-three/drei";

export default function Siemen(props) {
  const { nodes } = useGLTF("/holo_solo.glb");

  const material = new THREE.MeshPhysicalMaterial({
    color: new THREE.Color('#15C4E7').convertSRGBToLinear(),
    roughness: 0,
    clearcoat: 1,
    clearcoatRoughness: 0,
    transparent: true,
    opacity:0.4
  })
  return (
    <group {...props} dispose={null} scale={2}>
      <group name="Scene" >
      <mesh
          name="01siemens_"
          castShadow
          receiveShadow
          geometry={nodes["01siemens_"].geometry}
          material={material}
          position={[-5.904, 7.406, 0.522]}
          scale={1.077}
         />

 
      </group>
    </group>
  );
}

useGLTF.preload("/holo_solo.glb");
